/**
 * Morphology the passive-voice heuristic needs.
 *
 * PROVENANCE: hand-authored for this project. Nothing here is copied from write-good,
 * proselint, retext, or any other project — those carry licences we are not going to
 * inherit into a commercial product, and their lists are tuned for different tools.
 *
 * TUNING THIS LIST IS A PRODUCT DECISION, NOT A CODE CHANGE. Every entry here is something
 * the plugin will one day tell a paying customer is wrong with their writing. When one of
 * them argues, the argument is with this file. Pin the disputed phrase in
 * test/wordlist-fixtures.test.mjs before you change anything, so the next person can see
 * WHY an entry is in or out rather than guessing.
 */

/**
 * Past participles that do not end in -ed, so the passive rule can see "was
 * written" as well as "was published". Zero-change verbs (set, put, cut, hit) are
 * included: "the flag is set" is passive and worth a mark.
 *
 * Not listed: "had", "got", "gotten". "It was got" is not English, and including
 * them only invites noise around have/get idioms.
 */
export const IRREGULAR_PARTICIPLES = new Set([
	"arisen",
	"awoken",
	"beaten",
	"become",
	"been",
	"begun",
	"beheld",
	"bent",
	"bet",
	"bitten",
	"blown",
	"born",
	"borne",
	"bought",
	"broken",
	"brought",
	"built",
	"burnt",
	"burst",
	"cast",
	"caught",
	"chosen",
	"clung",
	"come",
	"cost",
	"crept",
	"cut",
	"dealt",
	"done",
	"drawn",
	"dreamt",
	"driven",
	"drunk",
	"dug",
	"dwelt",
	"eaten",
	"fallen",
	"felt",
	"fit",
	"flown",
	"flung",
	"forgiven",
	"forgotten",
	"forsaken",
	"fought",
	"found",
	"frozen",
	"given",
	"gone",
	"grown",
	"heard",
	"held",
	"hidden",
	"hit",
	"hung",
	"hurt",
	"kept",
	"knelt",
	"known",
	"laid",
	"led",
	"left",
	"lent",
	"let",
	"lost",
	"made",
	"meant",
	"met",
	"misled",
	"mistaken",
	"mown",
	"overcome",
	"overdone",
	"overseen",
	"overtaken",
	"paid",
	"proven",
	"put",
	"quit",
	"read",
	"redone",
	"ridden",
	"risen",
	"run",
	"said",
	"sat",
	"sawn",
	"seen",
	"sent",
	"set",
	"sewn",
	"shaken",
	"shot",
	"shown",
	"shrunk",
	"shut",
	"slain",
	"slept",
	"sold",
	"sought",
	"sown",
	"spent",
	"spilt",
	"split",
	"spoilt",
	"spoken",
	"spread",
	"sprung",
	"spun",
	"stolen",
	"struck",
	"stuck",
	"stung",
	"strewn",
	"strung",
	"sung",
	"sunk",
	"swept",
	"swollen",
	"sworn",
	"swung",
	"taken",
	"taught",
	"thought",
	"thrown",
	"thrust",
	"told",
	"torn",
	"understood",
	"undertaken",
	"undone",
	"upheld",
	"withdrawn",
	"withheld",
	"woken",
	"won",
	"worn",
	"wept",
	"wrought",
	"written",
]);

/**
 * Words that end in -ed but are nouns or adjectives, never a verb's participle.
 * Without this, "we need", "indeed", and "a hundred" all look like passives.
 *
 * Kept OFF this list on purpose: "learned", "blessed", "aged" in the verbal sense,
 * "freed", "fed". Each has a real passive reading ("the lesson was learned") and
 * suppressing them would cost a true positive far more often than it would save a
 * false one. "aged" is the one concession — "the wine was aged" is passive, but
 * "an aged oak" is common enough that we stay quiet.
 */
export const NON_PARTICIPLE_ED = new Set([
	"aged",
	"bed",
	"biped",
	"bled",
	"bloodshed",
	"bobsled",
	"bred",
	"breed",
	"creed",
	"crooked",
	"deed",
	"dogged",
	"embed",
	"exceed",
	"feed",
	"flatbed",
	"fled",
	"godspeed",
	"greed",
	"hatred",
	"heed",
	"hundred",
	"indeed",
	"jagged",
	"misdeed",
	"moped",
	"naked",
	"need",
	"proceed",
	"quadruped",
	"ragged",
	"red",
	"reed",
	"rugged",
	"sacred",
	"seaweed",
	"seed",
	"shed",
	"shred",
	"sled",
	"sped",
	"speed",
	"steed",
	"succeed",
	"tweed",
	"watershed",
	"wed",
	"weed",
	"wicked",
	"wretched",
]);
