/**
 * Curated word and phrase data for every rule. No logic lives here beyond freezing
 * and length-sorting the exports.
 *
 * Everything is hand-authored for this product. The bias throughout is toward
 * SILENCE: a word only earns a place on a list if flagging it would be defensible
 * in most sentences a real writer would type. Anything genuinely ambiguous is left
 * off (weasel/hedge/deslop) or added to a suppression list (adverb/passive).
 *
 * Conventions consumers rely on:
 * - Every entry is lowercase and trimmed. Callers lowercase the token first.
 * - Phrases use ASCII apostrophes and hyphens; callers must normalise curly
 *   quotes before matching, since Obsidian's smart-quote setting rewrites them.
 * - Phrase arrays are sorted longest-first so a naive scanner that takes the first
 *   match prefers "plays a crucial role" over "plays a".
 */

/** Longest-first, so overlapping phrases resolve to the more specific one. */
const byLength = (a, b) => b.length - a.length || a.localeCompare(b);

/**
 * Words ending in -ly that are not adverbs: nouns ("family", "assembly"), verbs
 * ("reply", "comply"), proper nouns ("July"), and the large class of -ly
 * ADJECTIVES ("friendly", "costly", "unlikely"). The adjectives matter most —
 * without them "a friendly reply from the family" reads as three adverbs.
 *
 * A handful of entries here (daily, weekly, likely, early) really can be adverbs.
 * We suppress them anyway: they are almost never the flabby -ly adverb the rule is
 * hunting for, and a false hit on "the daily standup" is worse than a missed hit.
 */
export const ADVERB_EXCEPTIONS = new Set([
	"ally",
	"anomaly",
	"apply",
	"assembly",
	"belly",
	"brotherly",
	"bubbly",
	"bully",
	"burly",
	"butterfly",
	"chilly",
	"comely",
	"comply",
	"costly",
	"cowardly",
	"crumbly",
	"curly",
	"daily",
	"deadly",
	"dolly",
	"dragonfly",
	"early",
	"elderly",
	"family",
	"fatherly",
	"firefly",
	"fly",
	"folly",
	"friendly",
	"ghastly",
	"ghostly",
	"gully",
	"hilly",
	"holly",
	"holy",
	"homely",
	"homily",
	"imply",
	"italy",
	"jelly",
	"jolly",
	"july",
	"leisurely",
	"likely",
	"lily",
	"lively",
	"lonely",
	"lovely",
	"manly",
	"melancholy",
	"molly",
	"monopoly",
	"monthly",
	"motherly",
	"multiply",
	"neighborly",
	"neighbourly",
	"nightly",
	"oily",
	"only",
	"orderly",
	"panoply",
	"ply",
	"portly",
	"prickly",
	"quarterly",
	"rally",
	"rely",
	"reply",
	"saintly",
	"scholarly",
	"sicily",
	"sickly",
	"silly",
	"sly",
	"stately",
	"sully",
	"supply",
	"surly",
	"tally",
	"timely",
	"ugly",
	"unlikely",
	"unruly",
	"unsightly",
	"weekly",
	"wily",
	"wobbly",
	"womanly",
	"woolly",
	"worldly",
	"wrinkly",
	"yearly",
]);

/**
 * Single-word hedges and qualifiers: they soften a claim without adding
 * information. Distinct from WEASEL_WORDS, which overstate one instead.
 *
 * Deliberately absent: "pretty" (adjective far more often than intensifier),
 * "clearly"/"obviously" (those overstate, so they live in WEASEL_WORDS), and
 * "about" (a preposition in most sentences).
 */
export const HEDGE_WORDS = new Set([
	"actually",
	"allegedly",
	"almost",
	"apparently",
	"approximately",
	"arguably",
	"basically",
	"conceivably",
	"essentially",
	"fairly",
	"generally",
	"hopefully",
	"just",
	"largely",
	"likely",
	"mainly",
	"marginally",
	"maybe",
	"moderately",
	"mostly",
	"nearly",
	"occasionally",
	"often",
	"ostensibly",
	"partially",
	"partly",
	"perhaps",
	"possibly",
	"potentially",
	"presumably",
	"probably",
	"purportedly",
	"quite",
	"rather",
	"really",
	"reportedly",
	"reputedly",
	"roughly",
	"seemingly",
	"slightly",
	"somehow",
	"somewhat",
	"sometimes",
	"supposedly",
	"theoretically",
	"typically",
	"unlikely",
	"usually",
	"very",
	"virtually",
]);

/**
 * Multiword hedges. Kept short and idiomatic; a phrase is only listed when the
 * sentence is stronger with it deleted outright.
 */
export const HEDGE_PHRASES = Object.freeze([
	"a bit",
	"a little bit",
	"as far as i can tell",
	"by and large",
	"for the most part",
	"give or take",
	"i believe",
	"i feel like",
	"i guess",
	"i suppose",
	"i think",
	"if you ask me",
	"in a sense",
	"in my opinion",
	"in my view",
	"in some ways",
	"it appears",
	"it could be argued",
	"it might be said",
	"it seems",
	"kind of",
	"more or less",
	"or something like that",
	"sort of",
	"to a certain extent",
	"to some extent",
	"up to a point",
].sort(byLength));

/**
 * Words that assert magnitude or consensus the sentence never earns: vague
 * quantifiers ("several", "many") and the adverbs that tell the reader how to
 * react ("obviously", "remarkably").
 *
 * No entry may also appear in HEDGE_WORDS — a token belongs to exactly one of the
 * two rules, or the same span gets marked twice with contradictory advice.
 */
export const WEASEL_WORDS = new Set([
	"absolutely",
	"certainly",
	"clearly",
	"considerably",
	"countless",
	"definitely",
	"dramatically",
	"drastically",
	"enormously",
	"exceedingly",
	"extremely",
	"few",
	"hugely",
	"immensely",
	"importantly",
	"incredibly",
	"interestingly",
	"literally",
	"many",
	"most",
	"notably",
	"numerous",
	"obviously",
	"relatively",
	"remarkably",
	"several",
	"significantly",
	"some",
	"substantially",
	"surely",
	"surprisingly",
	"tremendously",
	"undoubtedly",
	"utterly",
	"vast",
	"vastly",
	"various",
	"wildly",
]);

/**
 * Dead idioms and boardroom filler. Each one is a phrase a reader skims past, so
 * the mark is safe even when the sentence around it is fine.
 */
export const CLICHE_PHRASES = Object.freeze([
	"a double-edged sword",
	"a win-win",
	"all things considered",
	"at the drop of a hat",
	"at the end of the day",
	"at this point in time",
	"back to the drawing board",
	"beat around the bush",
	"boil the ocean",
	"circle back",
	"cut to the chase",
	"each and every",
	"easier said than done",
	"few and far between",
	"first and foremost",
	"food for thought",
	"going forward",
	"grasping at straws",
	"hit the ground running",
	"in a nutshell",
	"in this day and age",
	"last but not least",
	"leave no stone unturned",
	"level playing field",
	"low-hanging fruit",
	"move the needle",
	"needless to say",
	"off the beaten path",
	"only time will tell",
	"par for the course",
	"push the envelope",
	"raise the bar",
	"take it to the next level",
	"the best of both worlds",
	"the bottom line",
	"the calm before the storm",
	"the elephant in the room",
	"the fact of the matter",
	"the tip of the iceberg",
	"the writing on the wall",
	"think outside the box",
	"touch base",
	"when all is said and done",
	"when push comes to shove",
].sort(byLength));

/**
 * Vocabulary that reads as machine-generated. Inflections are listed explicitly
 * because the rule matches whole tokens and does not stem.
 *
 * The bar for entry is high: the word must be rare in ordinary human drafts and
 * near-compulsive in model output. Words like "important", "key", "explore", and
 * "navigate" are common LLM tells but far too common in honest prose to flag.
 */
export const DESLOP_WORDS = new Set([
	"beacon",
	"bustling",
	"comprehensive",
	"cornerstone",
	"crucial",
	"cultivate",
	"delve",
	"delves",
	"delving",
	"elevate",
	"elevates",
	"elevating",
	"embark",
	"embarking",
	"embarks",
	"empower",
	"empowering",
	"empowers",
	"ever-changing",
	"ever-evolving",
	"foster",
	"fostering",
	"fosters",
	"groundbreaking",
	"hallmark",
	"harness",
	"harnessing",
	"holistic",
	"illuminate",
	"indelible",
	"intricate",
	"intricacies",
	"invaluable",
	"landscape",
	"leverage",
	"leverages",
	"leveraging",
	"meticulous",
	"meticulously",
	"multifaceted",
	"myriad",
	"nuanced",
	"paramount",
	"pivotal",
	"plethora",
	"profound",
	"realm",
	"resonate",
	"robust",
	"seamless",
	"seamlessly",
	"showcase",
	"showcased",
	"showcases",
	"showcasing",
	"streamline",
	"streamlined",
	"synergy",
	"tapestry",
	"testament",
	"transformative",
	"underpin",
	"underpins",
	"underscore",
	"underscored",
	"underscores",
	"underscoring",
	"unlock",
	"unlocking",
	"unlocks",
	"unparalleled",
	"unwavering",
	"utilize",
	"utilizing",
	"vibrant",
	"vital",
]);

/**
 * Phrase-level LLM tells. The single-word connectives ("furthermore", "moreover")
 * live here rather than in DESLOP_WORDS so the whole rule can be tuned or muted as
 * one unit — they are the least offensive members of the set and the most likely
 * to be a deliberate choice by a human writer.
 */
export const DESLOP_PHRASES = Object.freeze([
	"a game-changer",
	"a myriad of",
	"a testament to",
	"a wide range of",
	"additionally",
	"as we've seen",
	"at the forefront of",
	"buckle up",
	"cutting-edge",
	"delve into",
	"dive deep",
	"embark on a journey",
	"ever-evolving landscape",
	"furthermore",
	"harness the power",
	"holistic approach",
	"in conclusion",
	"in summary",
	"in the ever-evolving",
	"in the realm of",
	"in today's fast-paced world",
	"it is important to note",
	"it is worth noting",
	"it's important to note",
	"it's worth noting",
	"key takeaways",
	"let's dive in",
	"look no further",
	"meticulously crafted",
	"moreover",
	"navigate the complexities",
	"paradigm shift",
	"plays a crucial role",
	"plays a vital role",
	"push the boundaries",
	"rich tapestry",
	"seamless integration",
	"shed light on",
	"stand the test of time",
	"that being said",
	"the possibilities are endless",
	"to summarize",
	"underscores the importance",
	"unlock the potential",
	"unwavering commitment",
	"when it comes to",
].sort(byLength));

/**
 * Past participles that do not end in -ed, so the passive rule can see "was
 * written" as well as "was published". Zero-change verbs (set, put, cut, hit) are
 * included: "the flag is set" is passive and worth a mark.
 *
 * Not listed: "had", "got", "gotten". "It was got" is not English, and including
 * them only invites noise around have/get idioms.
 */
export const IRREGULAR_PARTICIPLES = new Set([
	"arisen",
	"awoken",
	"beaten",
	"become",
	"been",
	"begun",
	"beheld",
	"bent",
	"bet",
	"bitten",
	"blown",
	"born",
	"borne",
	"bought",
	"broken",
	"brought",
	"built",
	"burnt",
	"burst",
	"cast",
	"caught",
	"chosen",
	"clung",
	"come",
	"cost",
	"crept",
	"cut",
	"dealt",
	"done",
	"drawn",
	"dreamt",
	"driven",
	"drunk",
	"dug",
	"dwelt",
	"eaten",
	"fallen",
	"felt",
	"fit",
	"flown",
	"flung",
	"forgiven",
	"forgotten",
	"forsaken",
	"fought",
	"found",
	"frozen",
	"given",
	"gone",
	"grown",
	"heard",
	"held",
	"hidden",
	"hit",
	"hung",
	"hurt",
	"kept",
	"knelt",
	"known",
	"laid",
	"led",
	"left",
	"lent",
	"let",
	"lost",
	"made",
	"meant",
	"met",
	"misled",
	"mistaken",
	"mown",
	"overcome",
	"overdone",
	"overseen",
	"overtaken",
	"paid",
	"proven",
	"put",
	"quit",
	"read",
	"redone",
	"ridden",
	"risen",
	"run",
	"said",
	"sat",
	"sawn",
	"seen",
	"sent",
	"set",
	"sewn",
	"shaken",
	"shot",
	"shown",
	"shrunk",
	"shut",
	"slain",
	"slept",
	"sold",
	"sought",
	"sown",
	"spent",
	"spilt",
	"split",
	"spoilt",
	"spoken",
	"spread",
	"sprung",
	"spun",
	"stolen",
	"struck",
	"stuck",
	"stung",
	"strewn",
	"strung",
	"sung",
	"sunk",
	"swept",
	"swollen",
	"sworn",
	"swung",
	"taken",
	"taught",
	"thought",
	"thrown",
	"thrust",
	"told",
	"torn",
	"understood",
	"undertaken",
	"undone",
	"upheld",
	"withdrawn",
	"withheld",
	"woken",
	"won",
	"worn",
	"wept",
	"wrought",
	"written",
]);

/**
 * Words that end in -ed but are nouns or adjectives, never a verb's participle.
 * Without this, "we need", "indeed", and "a hundred" all look like passives.
 *
 * Kept OFF this list on purpose: "learned", "blessed", "aged" in the verbal sense,
 * "freed", "fed". Each has a real passive reading ("the lesson was learned") and
 * suppressing them would cost a true positive far more often than it would save a
 * false one. "aged" is the one concession — "the wine was aged" is passive, but
 * "an aged oak" is common enough that we stay quiet.
 */
export const NON_PARTICIPLE_ED = new Set([
	"aged",
	"bed",
	"biped",
	"bled",
	"bloodshed",
	"bobsled",
	"bred",
	"breed",
	"creed",
	"crooked",
	"deed",
	"dogged",
	"embed",
	"exceed",
	"feed",
	"flatbed",
	"fled",
	"godspeed",
	"greed",
	"hatred",
	"heed",
	"hundred",
	"indeed",
	"jagged",
	"misdeed",
	"moped",
	"naked",
	"need",
	"proceed",
	"quadruped",
	"ragged",
	"red",
	"reed",
	"rugged",
	"sacred",
	"seaweed",
	"seed",
	"shed",
	"shred",
	"sled",
	"sped",
	"speed",
	"steed",
	"succeed",
	"tweed",
	"watershed",
	"wed",
	"weed",
	"wicked",
	"wretched",
]);

/**
 * Function words the echo detector ignores. Repeating "the" four times in a
 * paragraph is not an echo; repeating "landscape" is.
 */
export const STOPWORDS = new Set([
	"a",
	"about",
	"after",
	"again",
	"against",
	"all",
	"also",
	"am",
	"an",
	"and",
	"any",
	"are",
	"as",
	"at",
	"back",
	"be",
	"because",
	"been",
	"before",
	"being",
	"both",
	"but",
	"by",
	"can",
	"could",
	"did",
	"do",
	"does",
	"doing",
	"done",
	"down",
	"each",
	"even",
	"for",
	"from",
	"get",
	"gets",
	"go",
	"goes",
	"going",
	"got",
	"had",
	"has",
	"have",
	"he",
	"her",
	"here",
	"hers",
	"him",
	"his",
	"how",
	"i",
	"if",
	"in",
	"into",
	"is",
	"it",
	"its",
	"just",
	"let",
	"like",
	"make",
	"makes",
	"made",
	"may",
	"me",
	"might",
	"more",
	"most",
	"much",
	"must",
	"my",
	"no",
	"not",
	"now",
	"of",
	"off",
	"on",
	"once",
	"one",
	"only",
	"or",
	"other",
	"our",
	"ours",
	"out",
	"over",
	"own",
	"put",
	"same",
	"say",
	"says",
	"she",
	"should",
	"since",
	"so",
	"some",
	"still",
	"such",
	"take",
	"than",
	"that",
	"the",
	"their",
	"theirs",
	"them",
	"then",
	"there",
	"these",
	"they",
	"this",
	"those",
	"through",
	"to",
	"too",
	"two",
	"under",
	"until",
	"up",
	"us",
	"very",
	"was",
	"we",
	"well",
	"were",
	"what",
	"when",
	"where",
	"which",
	"while",
	"who",
	"whom",
	"why",
	"will",
	"with",
	"would",
	"you",
	"your",
	"yours",
]);
